spring.application.name=donation-modulith
spring.http.port=8082
#spring.flyway.enabled=false
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.datasource.url=jdbc:postgresql://localhost:5432/qatra_db
spring.datasource.username=qatra
spring.datasource.password=qatra

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=donation-service
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

app.kafka.topic.notification-requests=qatra.notification.requests

# Show generated SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Export schema to a file (this will generate create.sql in your project root)
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=target/generated-schema.sql
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-source=metadata

# Also log the DDL statements
logging.level.org.hibernate.tool.schema.spi=DEBUG
logging.level.org.hibernate.tool.schema.internal=DEBUG

# DevTools Configuration
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.display-request-duration=true
springdoc.show-actuator=true

# Spring Modulith OpenAPI Configuration
springdoc.group-configs[0].group=donation-modulith
springdoc.group-configs[0].paths-to-match=/api/v1/**
